version: '3'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5
    container_name: readarr-requests-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: readarr-requests-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - READARR_API_URL=${READARR_API_URL}
      - READARR_API_KEY=${READARR_API_KEY}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
      - ADMIN_KEY=${ADMIN_KEY}

  # Frontend App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=/api
    container_name: readarr-requests-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app_network

  # Nginx Web Server (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: readarr-requests-nginx
    restart: unless-stopped
    ports:
      - "${EXTERNAL_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local